/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import java.io.File;
import javax.swing.JFileChooser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.Timer;
/**
 *
 * @author Mariano Rack
 */
public class JavaP2 extends javax.swing.JFrame {
    Thread hilo = new hilo1("Burbuja Ascendente");
     Thread hilo2 = new hilo2("Burbuja Descendente");
     Thread hilo3 = new hilo3("Insertion Ascendente");
     Thread hilo4 = new hilo4("Insertion Descendente");
private BufferedReader lector;
    private String linea,linea2;
    private static String partes[]=null,partes2[]=null, matriz[][]= new String[100][2],titulos[]=null,titulosd[]=null,encabezados[]=null;
private Timer t;
    private int h, m, s, cs;
    private static int valores[]=null,valoresd[]=null;
 String nom,t1,t2;
 int valor,pasos=0,l;
 private ActionListener acciones = new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent ae) {
            ++cs; 
            if(cs==100){
                cs = 0;
                ++s;
            }
            if(s==60) 
            {
                s = 0;
                ++m;
            }
            if(m==60)
            {
                m = 0;
                ++h;
            }
            actualizarLabel();
        }
        
    };
 private void actualizarLabel() {
        String tiempo = (h<=9?"0":"")+h+":"+(m<=9?"0":"")+m+":"+(s<=9?"0":"")+s+":"+(cs<=9?"0":"")+cs;
        lbtimer.setText(tiempo);
    }
    /**
     * Creates new form JavaP2
     */
    public JavaP2() {
        initComponents();
        btalgo.add(burbu);
        btalgo.add(insert);
        orden.add(desc);
        orden.add(asc);
        t = new Timer(10, acciones);
    }
public void initcomponents2(){
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btalgo = new javax.swing.ButtonGroup();
        orden = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtruta = new javax.swing.JTextField();
        txttitulo = new javax.swing.JTextField();
        btordenar = new javax.swing.JButton();
        btgenerar = new javax.swing.JButton();
        btexam = new javax.swing.JButton();
        grafica = new javax.swing.JPanel();
        burbu = new javax.swing.JRadioButton();
        insert = new javax.swing.JRadioButton();
        asc = new javax.swing.JRadioButton();
        desc = new javax.swing.JRadioButton();
        lbtimer = new javax.swing.JLabel();
        lbpasos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btreporte = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btordenar.setBackground(new java.awt.Color(255, 51, 51));
        btordenar.setFont(new java.awt.Font("Simpsonfont", 1, 14)); // NOI18N
        btordenar.setForeground(new java.awt.Color(0, 0, 0));
        btordenar.setText("Ordenar");
        btordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btordenarActionPerformed(evt);
            }
        });

        btgenerar.setBackground(new java.awt.Color(255, 51, 51));
        btgenerar.setFont(new java.awt.Font("Simpsonfont", 1, 14)); // NOI18N
        btgenerar.setForeground(new java.awt.Color(0, 0, 0));
        btgenerar.setText("Generar");
        btgenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgenerarActionPerformed(evt);
            }
        });

        btexam.setBackground(new java.awt.Color(255, 51, 51));
        btexam.setFont(new java.awt.Font("Simpsonfont", 1, 14)); // NOI18N
        btexam.setForeground(new java.awt.Color(0, 0, 0));
        btexam.setText("Examinar");
        btexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexamActionPerformed(evt);
            }
        });

        grafica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout graficaLayout = new javax.swing.GroupLayout(grafica);
        grafica.setLayout(graficaLayout);
        graficaLayout.setHorizontalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        graficaLayout.setVerticalGroup(
            graficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        burbu.setFont(new java.awt.Font("Simpsonfont", 1, 14)); // NOI18N
        burbu.setForeground(new java.awt.Color(0, 0, 0));
        burbu.setText("Burbuja");

        insert.setFont(new java.awt.Font("Simpsonfont", 1, 14)); // NOI18N
        insert.setForeground(new java.awt.Color(0, 0, 0));
        insert.setText("Insertion");

        asc.setBackground(new java.awt.Color(255, 255, 255));
        asc.setFont(new java.awt.Font("Simpsonfont", 1, 14)); // NOI18N
        asc.setForeground(new java.awt.Color(0, 0, 0));
        asc.setText("Ascendente");

        desc.setBackground(new java.awt.Color(255, 255, 255));
        desc.setFont(new java.awt.Font("Simpsonfont", 1, 14)); // NOI18N
        desc.setForeground(new java.awt.Color(0, 0, 0));
        desc.setText("Descendente");

        lbtimer.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        lbtimer.setForeground(new java.awt.Color(255, 255, 0));
        lbtimer.setText("00:00:00:00");

        lbpasos.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        lbpasos.setForeground(new java.awt.Color(255, 255, 0));
        lbpasos.setText("0");

        jLabel1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Orden:");

        jLabel2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Pasos:");

        jLabel3.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Tiempo:");

        jLabel4.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Titulo::");

        jLabel6.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Ruta:");

        jLabel7.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Algoritmo: ");

        btreporte.setBackground(new java.awt.Color(255, 51, 51));
        btreporte.setFont(new java.awt.Font("Simpsonfont", 1, 14)); // NOI18N
        btreporte.setForeground(new java.awt.Color(0, 0, 0));
        btreporte.setText("Reporte");
        btreporte.setEnabled(false);
        btreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreporteActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p/barsinzo.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p/homerdonuts.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbtimer)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbpasos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtruta)
                                    .addComponent(txttitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btexam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btgenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btordenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btreporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(insert)
                                .addComponent(burbu)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desc)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1))
                            .addComponent(asc))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btexam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(burbu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(insert))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(asc)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(desc))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(btgenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbtimer)
                            .addComponent(lbpasos)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        jLabel4.getAccessibleContext().setAccessibleName("Titulo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexamActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
/*
* De acuerdo con JFileChooser para seleccionar el cuadro de carpeta emergente 1. Sólo seleccione el directorio JFileChooser.DIRECTORIES_ONLY
 * 2. Seleccione solo el archivo JFileChooser.FILES_ONLY
 * 3. Tanto los directorios como los archivos pueden ser JFileChooser.FILES_AND_DIRECTORIES
*/

 
 
 // Guardar el directorio seleccionado chooser.showSaveDialog (parent);
Component parent = null;
int returnVal = chooser.showSaveDialog(parent);
 
 
 // Obtener el objeto de archivo seleccionado JFileChooser.APPROVE_OPTION
 // Si el directorio guardado es consistente con el objeto de archivo seleccionado, devolverá 0 si tiene éxito
if (returnVal == JFileChooser.APPROVE_OPTION) {
 
 
 // obtener ruta
String selectPath = chooser.getSelectedFile().getPath();
 txtruta.setText(selectPath);
}

    }//GEN-LAST:event_btexamActionPerformed

    private void btgenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgenerarActionPerformed
        // TODO add your handling code here:
         
         DefaultCategoryDataset datos = new DefaultCategoryDataset();
        try{
            lector = new BufferedReader(new FileReader(txtruta.getText()));
            
           linea2 = lector.readLine();
           partes2=linea2.split(",");
            t1=partes2[0];
             t2=partes2[1];
       while ((linea = lector.readLine()) !=null){  
          partes = linea.split(",");
          l++;
           System.out.println();
           for(int i =0; i < partes.length; i++){
               
            String p=partes[0];
            String valor=partes[1];
             int num = Integer.parseInt(valor);
             matriz[0][0]=partes[0];
              matriz[0][1]=partes[1];
              for(int j =0; j <100;j++){
                  if(matriz[j][0]!=null){
                      matriz[j][0]=partes[0];
                               matriz[j][1]=partes[1];
                              
         
                  int nume = Integer.parseInt(matriz[j][1]);
        datos.setValue(nume,matriz[j][0],matriz[j][0]);
        
 
        JFreeChart graf = ChartFactory.createBarChart3D(
                txttitulo.getText(),
                t1,
                 t2,
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        ChartPanel grafica1 = new ChartPanel(graf);
        grafica1.setMouseWheelEnabled(true);
        grafica1.setPreferredSize(new Dimension(800,400));
        grafica.setLayout(new BorderLayout());
        grafica.add(grafica1,BorderLayout.NORTH);
        pack();
        repaint();
                  }
              }
    }
       }
       lector.close();
       linea = null;
       partes = null;
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(  null, e);
    }
    }//GEN-LAST:event_btgenerarActionPerformed
private void BurbujaAsc(){
    boolean termino = true;
    for(int i=0;i<matriz.length;i++){
        if(matriz[i]!=null && matriz[i+1] !=null){
            int valor = Integer.parseInt(matriz[i][1]);
            int valor2 = Integer.parseInt(matriz[i+1][1]);
           String aux=matriz[i][0];
            
           if(valor>valor2){
               valor=valor2;
               matriz[i][0]=matriz[i+1][0];
               matriz[i+1][0]=""+valor;
               matriz[i+1][0]=aux;
                       
                       
           }
        }
        
       
    }
}
private void modificargrafica() {
        grafica.removeAll();
        DefaultCategoryDataset datos = new DefaultCategoryDataset();

        for (int i = 0; i < titulos.length; i++) {
            if (titulos[i] != null) {
                datos.setValue(valores[i], titulos[i], titulos[i]);
            }
        }

        JFreeChart grafico = ChartFactory.createBarChart3D(txttitulo.getText(),
                t1,
                t2,
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false);

        ChartPanel panel = new ChartPanel(grafico);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(800, 400));
        grafica.setLayout(new BorderLayout());
        grafica.add(panel, BorderLayout.NORTH);
        pack();
        repaint();
    }
    private void btordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btordenarActionPerformed
        // TODO add your handling code here
        //
        if(burbu.isSelected()==true && asc.isSelected()==true){
            t.start();
hilo.start();
btreporte.setEnabled(true);
        }
        if(burbu.isSelected()==true && desc.isSelected()==true){
            t.start();
hilo2.start();
btreporte.setEnabled(true);
        }
         if(insert.isSelected()==true && asc.isSelected()==true){
            t.start();
hilo3.start();
btreporte.setEnabled(true);
        }
         if(insert.isSelected()==true && desc.isSelected()==true){
            t.start();
hilo4.start();
btreporte.setEnabled(true);
        }
          
    }//GEN-LAST:event_btordenarActionPerformed

    private void btreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreporteActionPerformed
        // TODO add your handling code here:
        String algoritmo="";
        if(burbu.isSelected()==true && asc.isSelected()==true)
        {
        algoritmo="Burbuja Ascendente";
            
        }
        if(burbu.isSelected()==true && desc.isSelected()==true)
        {
        algoritmo="Burbuja Descendente";
            
        }
        if(insert.isSelected()==true && asc.isSelected()==true){
            algoritmo="Insertion Ascendente";
        }
        if(insert.isSelected()==true && desc.isSelected()==true){
            algoritmo="Insertion Descendente";
        }

            String cadenaHTML = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"  
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte</title>\n"
                + "</head>\n"
                + "<body bgcolor=\"#33AFFF\">\n"
        +"<p><font face=\"Luminari, fantasy\"><H1 align=\"center\" style=\"color:#C92C05;font-size: 40px;\">  Mariano Roberto Rac Noguera Carnet:202101149 </H1></p>\n"
                +"<p><font face=\"Luminari, fantasy\"><H1 align=\"center\" style=\"color:#C92C05;font-size: 40px;\"> Algoritmo:"+algoritmo+" , Tiempo: "+lbtimer.getText()+", Pasos: "+lbpasos.getText()+"</H1></p>\n"
                + "<table border = \"2\" CELLPADDING = 15 align = \"center\">\n"
                + "        <tr>"
                + "          <th>Eje X Ordenados</th>\n"
                + "          <th>Eje Y Ordenados</th>\n"
                     + "          <th>Eje X Desordenados</th>\n"
                + "          <th>Eje Y Desordenados</th>\n"

                + "        </tr>";
for(int i=0;i<valores.length;i++){
    cadenaHTML += "<tr>";
                cadenaHTML += "  <td>" + titulos[i]+ "</td>";
                cadenaHTML += "  <td>" + valores[i]+ "</td>";
                cadenaHTML += "  <td>" + titulosd[i]+ "</td>";
                cadenaHTML += "  <td>" + valoresd[i]+ "</td>";
        }
        cadenaHTML += "</tr>";  
        cadenaHTML += "      </table>\n"
                + "</body>\n"
                + "</html>";

        File archivo = new File("Reporte.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
            bw.write(cadenaHTML);
            bw.close();
        } catch (Exception e) {
        }             // TODO add your handling code here:
        
    }//GEN-LAST:event_btreporteActionPerformed
public void actionPerformed(ActionEvent ae) {
            ++cs; 
            if(cs==100){
                cs = 0;
                ++s;
            }
            if(s==60) 
            {
                s = 0;
                ++m;
            }
            if(m==60)
            {
                m = 0;
                ++h;
            }
            actualizarLabel();
        }
public class hilo1 extends Thread{
    public hilo1 (String msg){  
        super(msg);
    }
   public void run() {
 
       try {
            lector = new BufferedReader(new FileReader(txtruta.getText()));
            String linea = "";
            int total = 0;
            while (linea != null) {
                linea = lector.readLine();
                total++;
            }
            titulosd = new String[total - 1];
            titulos = new String[total - 1];
            valoresd = new int[total - 1];
            valores = new int[total - 1];
            encabezados = new String[2];
            int ahora = 0;
            lector = new BufferedReader(new FileReader(txtruta.getText()));
            linea = lector.readLine();
            while (linea != null) {
                String[] datosd = linea.split(",");
                String[] datoso = linea.split(",");
                if (datosd.length == 2 && ahora > 0) {
                    titulosd[ahora] = datosd[0];
                    titulos[ahora] = datoso[0];
                    valoresd[ahora] = Integer.parseInt(datosd[1]);
                    valores[ahora] = Integer.parseInt(datoso[1]);
                    ahora++;
                } else if (datosd.length == 2 && ahora == 0) {
                    encabezados[0] = datosd[0];
                    encabezados[1] = datosd[1];
                    ahora++;
                }
                linea = lector.readLine();
            }
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
 pasos =0;
 
        boolean termino = false;
        while (!termino) {
            termino = true;
            for (int i = 1; i < titulos.length-1; i++) {
                int d=i+1;
                while(titulos[d] == null){
                    d++;
                }
                if (titulos[i] != null) {
                    int valor = valores[i];
                    String aux = titulos[i];
                    if (valores[i] > valores[d]) {
                        termino = false;
                        valores[i] = valores[d];
                        titulos[i] =titulos[d];
                        valores[d] = valor;
                        titulos[d] = aux;
                        i=d;
                        pasos++;
                        lbpasos.setText(String.valueOf(pasos));
                        try {
             Thread.sleep(1000); 
       } catch (InterruptedException e) {
JOptionPane.showMessageDialog(  null, e);
       }
                        modificargrafica();
          
                        
                    }
                }
            }
        }
        if(t.isRunning()) 
        {
            t.stop();
            
        }
        
        actualizarLabel();
        h=0; m=0; s=0; cs=0;
   }
       
}
public class hilo2 extends Thread{
    public hilo2 (String msg){  
        super(msg);
    }
   public void run() {
      
       try {
            lector = new BufferedReader(new FileReader(txtruta.getText()));
            String linea = "";
            int total = 0;
            while (linea != null) {
                linea = lector.readLine();
                total++;
            }
            titulosd = new String[total - 1];
            titulos = new String[total - 1];
            valoresd = new int[total - 1];
            valores = new int[total - 1];
            encabezados = new String[2];
            int ahora = 0;
            lector = new BufferedReader(new FileReader(txtruta.getText()));
            linea = lector.readLine();
            while (linea != null) {
                String[] datosd = linea.split(",");
                String[] datoso = linea.split(",");
                if (datosd.length == 2 && ahora > 0) {
                    titulosd[ahora] = datosd[0];
                    titulos[ahora] = datoso[0];
                    valoresd[ahora] = Integer.parseInt(datosd[1]);
                    valores[ahora] = Integer.parseInt(datoso[1]);
                    ahora++;
                } else if (datosd.length == 2 && ahora == 0) {
                    encabezados[0] = datosd[0];
                    encabezados[1] = datosd[1];
                    ahora++;
                }
                linea = lector.readLine();
            }
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
 pasos =0;
 
        boolean termino = false;
        while (!termino) {
            termino = true;
            for (int i = 1; i < titulos.length-1; i++) {
                int d=i+1;
                while(titulos[d] == null){
                    d++;
                }
                if (titulos[i] != null) {
                    int valor = valores[i];
                    String aux = titulos[i];
                    if (valores[i] < valores[d]) {
                        termino = false;
                        valores[i] = valores[d];
                        titulos[i] =titulos[d];
                        valores[d] = valor;
                        titulos[d] = aux;
                        i=d;
                        pasos++;
                        lbpasos.setText(String.valueOf(pasos));
                        try {
             Thread.sleep(1000); 
       } catch (InterruptedException e) {
JOptionPane.showMessageDialog(  null, e);
       }
                        modificargrafica();
          
                        
                    }
                }
            }
        }
        if(t.isRunning()) 
        {
            t.stop();
            
        }
        
        actualizarLabel();
        h=0; m=0; s=0; cs=0;
       
   }
   }
public class hilo3 extends Thread{
    public hilo3 (String msg){  
        super(msg);
    }
   public void run() {
      
       try {
            lector = new BufferedReader(new FileReader(txtruta.getText()));
            String linea = "";
            int total = 0;
            while (linea != null) {
                linea = lector.readLine();
                total++;
            }
            titulosd = new String[total - 1];
            titulos = new String[total - 1];
            valoresd = new int[total - 1];
            valores = new int[total - 1];
            encabezados = new String[2];
            int ahora = 0;
            lector = new BufferedReader(new FileReader(txtruta.getText()));
            linea = lector.readLine();
            while (linea != null) {
                String[] datosd = linea.split(",");
                String[] datoso = linea.split(",");
                if (datosd.length == 2 && ahora > 0) {
                    titulosd[ahora] = datosd[0];
                    titulos[ahora] = datoso[0];
                    valoresd[ahora] = Integer.parseInt(datosd[1]);
                    valores[ahora] = Integer.parseInt(datoso[1]);
                    ahora++;
                } else if (datosd.length == 2 && ahora == 0) {
                    encabezados[0] = datosd[0];
                    encabezados[1] = datosd[1];
                    ahora++;
                }
                linea = lector.readLine();
            }
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
 pasos =0;
   int n = valores.length;  
        for (int j = 1; j < n; j++) {  
            int key = valores[j]; 
            String key1=titulos[j];
            int i = j-1;  
            while ( (i > -1) && ( valores [i] > key ) ) {  
                valores[i+1] =  valores [i];  
                titulos[i+1] = titulos[i];  
                i--;  
            }  
            valores[i+1] = key; 
            titulos[i+1]=key1;
            pasos++;
             lbpasos.setText(String.valueOf(pasos));
              try {
             Thread.sleep(1000); 
       } catch (InterruptedException e) {
JOptionPane.showMessageDialog(  null, e);
       }
                        modificargrafica();
          
        }  
         modificargrafica();
  
        if(t.isRunning()) 
        {
            t.stop();
            
        }
        
        actualizarLabel();
        h=0; m=0; s=0; cs=0;
       
   }
   }
public class hilo4 extends Thread{
    public hilo4 (String msg){  
        super(msg);
    }
   public void run() {
      
       try {
            lector = new BufferedReader(new FileReader(txtruta.getText()));
            String linea = "";
            int total = 0;
            while (linea != null) {
                linea = lector.readLine();
                total++;
            }
            titulosd = new String[total - 1];
            titulos = new String[total - 1];
            valoresd = new int[total - 1];
            valores = new int[total - 1];
            encabezados = new String[2];
            int ahora = 0;
            lector = new BufferedReader(new FileReader(txtruta.getText()));
            linea = lector.readLine();
            while (linea != null) {
                String[] datosd = linea.split(",");
                String[] datoso = linea.split(",");
                if (datosd.length == 2 && ahora > 0) {
                    titulosd[ahora] = datosd[0];
                    titulos[ahora] = datoso[0];
                    valoresd[ahora] = Integer.parseInt(datosd[1]);
                    valores[ahora] = Integer.parseInt(datoso[1]);
                    ahora++;
                } else if (datosd.length == 2 && ahora == 0) {
                    encabezados[0] = datosd[0];
                    encabezados[1] = datosd[1];
                    ahora++;
                }
                linea = lector.readLine();
            }
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
 pasos =0;
   int n = valores.length;  
        for (int j = 1; j < n; j++) {  
            int key = valores[j]; 
            String key1=titulos[j];
            int i = j-1;  
            while ( (i > -1) && ( valores [i] < key ) ) {  
                valores[i+1] =  valores [i];  
                titulos[i+1] = titulos[i];  
                i--;  
            }  
            valores[i+1] = key; 
            titulos[i+1]=key1;
            pasos++;
             lbpasos.setText(String.valueOf(pasos));
              try {
             Thread.sleep(1000); 
       } catch (InterruptedException e) {
JOptionPane.showMessageDialog(  null, e);
       }
                        modificargrafica();
          
        }  
         modificargrafica();
  
        if(t.isRunning()) 
        {
            t.stop();
            
        }
        
        actualizarLabel();
        h=0; m=0; s=0; cs=0;
       
   }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton asc;
    private javax.swing.ButtonGroup btalgo;
    private javax.swing.JButton btexam;
    private javax.swing.JButton btgenerar;
    private javax.swing.JButton btordenar;
    private javax.swing.JButton btreporte;
    private javax.swing.JRadioButton burbu;
    private javax.swing.JRadioButton desc;
    private javax.swing.JPanel grafica;
    private javax.swing.JRadioButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbpasos;
    private javax.swing.JLabel lbtimer;
    private javax.swing.ButtonGroup orden;
    private javax.swing.JTextField txtruta;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
